### PR TITLE
Disable tests for the kFreeBSD backend of Mirage.

### PR DESCRIPTION
**Pull request by pgj**
I had to conditionally disable the bundled tests as the corresponding binaries cannot be built properly with the Mirage/kFreeBSD cross-compiler.  This change should not affect other cases.

### CODE REVIEW

**Comment by avsm** [comment]
Hm, how about standardising on an environment variable that we can set in the OPAM compiler switch?

For instance a NO_EXECUTABLES could be used to disable anything that tries to build an elf binary (including tests, but also perhaps other tools)

**Comment by pgj** [comment]
Building ELF binaries fail only in certain cases, but they may be needed for some the OPAM packages, e.g. `mirari`.  I could not really track down the causes, as the build usually fails somewhere around `ocamldep(1)` when it cannot create the `.depends` file for one of the sources, simply dies from a mysterious "Signal -8" instead.

**Comment by avsm** [comment]
Right -- but host packages shouldn't be built in the kFreeBSD compiler switch.  We really ought to be using a host Mirari instead.

-anil

**Comment by pgj** [comment]
This is not clear yet for me how a host Mirari could be used with OPAM.  All the Mirage/kFreeBSD packages are built with the dedicated cross-compiler at the moment -- switching back to a different toolchain would imply "hiding" `mirari` from the `PATH`, I think.

FreeBSD does not have `mirari` ported at the moment, so it cannot be just installed as the system OCaml compiler or OPAM itself.  Looking at the dependencies, `mirari` would require adding at least the following packages (and their dependencies) to the FreeBSD ports tree: `tuntap`, `fd-send-recv`, `cmdliner` -- not mentioning that `mirage-www` basically depends on `mirari` as a package.

Please do not get me wrong, I am not against the idea of generalization, I just do not see how it fits into the current workflow.  I am open to suggestions on how to adapt the workflow on FreeBSD.

**Comment by avsm** [comment]
I'm thinking that we should compile and install Mirari separately from OPAM for this purpose, so that it's installed globally.  I think we need a few more opinions on this, as we _could_ have some sort of a hook in OPAM to do a more global installation -- could you raise on the mailing list?

-a

**Comment by pgj** [comment]
Right.  I can send a mail on this to the `cl-mirage` list to initiate some discussion on OPAM global installs.

Regarding this pull request: I guess I shall rework the patch to watch for `NO_EXECUTABLE` instead (and add that environment variable to the `.comp` file of the Mirage/kFreeBSD cross-compiler) -- as `mirari` (and no other package) does not use it at the moment, that version would not break anything, I believe.

**Pull request closed without merging**
